version: '3'

services:
  prometheus:
    image: bitnami/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
    environment:
      - HOST_DOCKER_INTERNAL=host.docker.internal

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
    environment:
      - HOST_DOCKER_INTERNAL=host.docker.internal

volumes:
  grafana_data:
