global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['host.docker.internal:3030']
  - job_name: 'user'
    static_configs:
      - targets: ['host.docker.internal:3031']
